language: python
python: 3.6
matrix:
  include:
  - sudo: required
    services:
    - docker
    env:
    - PIP=pip
    - CIBW_SKIP=cp27-*
    - CIBW_TEST_COMMAND="pytest /project/tests/tests.py"
  - os: osx
    language: generic
    env:
    - PIP=pip2
    - CIBW_SKIP=cp27-*
    - CIBW_TEST_COMMAND="pytest /Users/travis/build/segfault/ultrajson/tests/tests.py"
env:
  global:
  - CIBW_TEST_REQUIRES=pytest
  - TWINE_USERNAME=segfaults
  - secure: CeL10453dNm05+scw4pJuj6iT0W2Rra5sY/z6SjkUopp4XFkPME1j1JTdLRGN9o8Hns6xzzOtL0mAIK1W2iUzotGqXRBOWxtU5QNY06lM+02hupy41BFgw4HFpsyz2NyDE8vH8WaA3KPPqVKw6ZDV3lTLzMys6ZTBHWhUdRnC40u6LM/iwEbrd5xyofHiV5N1P6gUQyfgJw/jLBPJgTRxjpGIdzymlSfiM+h1Cgg20WD0qiTZtJl/3tbJlQWkZS5n2PiR12+uzOS2y+A/2jSNQQHW/s05W7KEoj+KJiVBUjp+BbnNewb/1Fo8MTGcXgV/pWnzGxk0Stiu3laqXsYQU7LUnuspqBH9CxKgjFfN9eKE+IwrMrZt4Wdhw4uwEPo1x2/ExAOFDABCoqrOGyOTSADAM31O7zgchXeGySIut+5kzfYafN1iYagHMdQkzvZPOrthPV3axVMZWUoFirLuDa3jrbsyAofq2WbuOvcXFQFdpJBDA+LwblVxu0OFe9ZuJkTw5V1IWy6qONbdu+IEQNS61ZEVixnEmWxaOlTyI1yG1Zx3XSr+zfGDnOreculwEJbyYTkZuGWDs8HpLDqM5ebsYBUWdPpWjPqLWLMa9FQFLLEzSVcDhZAsMXHBXLrvi2+U644btOansOCPnkr6oYAm4qN17kL0sqWgvaWZWQ=
  - secure: WNqFAnkaxFVwM+Tdd5TpLYe55/UZ63/wnLZ9BnvKRZOuV6amF0QXlA/YUeTgxdjHOehhsbLMKDMjKS6vspx07lHG47PhmRittP5PkJXg3fas7eMzprbIgickJCJDdHA1aXtcKDvdKRCLA1zcuxiQDIUgSfBGGKHIwZZypWlfVZMBlIm2Sbib7w2hzbYlUNE+VkCqXtNuoJ6+NGMJLtwpIc3VZpm8ttgJ0WchZTW4dH6CXRaW/P7QWZ4y2DvuYxm4yAFuKOmcT8+qKy2ICh2bvfjGQtr+TCFEFy+n1meqZIWBHYdTH30YzBVAlRUmH/v9w7X5aoRgtKphbJ5onBJair2XW/eu4mGXeryZycdK/vcQ5O0YW26VP2e6HcY0EIzKmPZVyb01Z9D+6+2CQLxMiFR21dwtJUNMoDIrjM9i0O4ReMeIwCi3am+8tOrEvmOo+s8CwG5FnZ1rFqjTJwNL+Sc3ilADSqreZzNhTqJBovmGjnoh6lTD/1oIXrQk7hEQCEva3DVF9yUJAvgFSK6nP5+JQE08NcRwy+sW6aYdCZhLSVElHzzy9YofRDGxqqFAkxv2jS+0L256pW0eAUgD2LCPPJkNbxpEOXd+sVWg40Ag+JxAWR8GQxIvlD8Mxk50D9vKsx0I7aG12yu/3hTFHPr0X/Eza3aQJPNgBXClbnc=
script:
- "$PIP install cibuildwheel==0.10.1"
- echo "#define UJSON_VERSION \"2.1.${TRAVIS_BUILD_NUMBER}\"" > python/version.h
- export CIBW_ENVIRONMENT="CI=\"$CI\" TRAVIS_BRANCH=\"$TRAVIS_BRANCH\" TRAVIS_COMMIT=\"$TRAVIS_COMMIT\""
- cibuildwheel --output-dir wheelhouse
- |
  if [[ ! -z "$TRAVIS_TAG" ]]; then
    $PIP install twine
    python -m twine upload wheelhouse/*.whl --skip-existing
  elif [[ "$TRAVIS_BRANCH" = "master" ]] && [[ -z "$TRAVIS_PULL_REQUEST_SHA" ]]; then
    export TWINE_USERNAME=segfault
    export TWINE_PASSWORD="$TWINE_TEST_PASSWORD"
    $PIP install twine
    python -m twine upload wheelhouse/*.whl --repository-url https://test.pypi.org/legacy/ --skip-existing
  fi
notifications:
  slack:
    secure: adph3tDEsKVxHQwR+5fdFpnnmt0xOfxpQXt2NkoJ9RS0u4bIXaYvwIUVc2vJ/QJyeIQEGV7/I2aDD3WTaJEUzH52OXIiK5cxmL2pML+1OJTrpuL9JAUgOYDbQyb6OiqgFDIBTACqWWnjqQWC8syqlh9JrAhVSmwLCix27CuELiu4c6RnN/Hp7oCPg2lvqNm1/hxK03+WAoY/FiOqZsAAM9DwZLe6RdJEYZQI2shO1XjAY9uZRN94jatpEjRiogDtzQizJI5gwSL96WXijTpppkEJ4jhlSu3zwgNZCM4Yx6bDRaYG2LFOTQN2q9cxpy0fS9USgYyu2QkOJmCi/gF2GFWhjhhfANY6vnYYqT2i87GhvBY1GJl4YYnFdSomJv0O/D9M04aAMJDqmoNAz3RGEVN+2w4prWCGlpNgy4RMZDV3bhtoH8ULxlrwl4PX8fpvrIuwCqv5PQRUFvWPKFKRqo7BeKuayIzFEIXcfdSeDFQcfYFQmN+fg0OC3kVawDJMVM/1WLAxvcA0iClIyyJdWEODk6WwpoQnYOGORL1/k+O9OQFaoRSTOm5Nn/QksL8m4gn6Py7eC0R3Bh00K253iXuPHz6O8Itxor7wLSCRNSXhv+wynfbVa8sPPoWOyPy1wuD30HGfD8WzjSNaA/iUWoeTtrSXAVjfK/KPLEzD99A=
